spring:
  application:
    name: fitness

  datasource:
    url: jdbc:mysql://localhost:3306/fitness
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9090

eureka:
  client:
       
    service-url:
      defaultZone: http://localhost:8761/eureka/
