
spring:
  application:
    name: aiservice

  data:
    mongodb:
      uri: 
      database: fitnessrecommendation

server:
  port: 7171

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
