spring:
  application:
    name: activity

  data:
    mongodb:
      uri:
      database: fitnessactivity

server:
  port: 9191

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
